// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCksmzI2B_RJx18QoOVmc3SAtir1UYyJYU',
    appId: '1:895538475573:web:502aca2d5465dccdc2b77c',
    messagingSenderId: '895538475573',
    projectId: 'hamqadam-13e2b',
    authDomain: 'hamqadam-13e2b.firebaseapp.com',
    storageBucket: 'hamqadam-13e2b.firebasestorage.app',
    measurementId: 'G-4MPDV8V7CY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDrSqMn2lvBNqpoj5PkCeHkYhhic0r9pw',
    appId: '1:895538475573:android:8e66d73b1e91863ec2b77c',
    messagingSenderId: '895538475573',
    projectId: 'hamqadam-13e2b',
    storageBucket: 'hamqadam-13e2b.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0_B9QTh3HAkrOggR3aLej6_l9VQlBGBw',
    appId: '1:895538475573:ios:a8a79428e16384edc2b77c',
    messagingSenderId: '895538475573',
    projectId: 'hamqadam-13e2b',
    storageBucket: 'hamqadam-13e2b.firebasestorage.app',
    iosBundleId: 'com.app.hamqadam',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0_B9QTh3HAkrOggR3aLej6_l9VQlBGBw',
    appId: '1:895538475573:ios:65f96e1137b1d6e1c2b77c',
    messagingSenderId: '895538475573',
    projectId: 'hamqadam-13e2b',
    storageBucket: 'hamqadam-13e2b.firebasestorage.app',
    iosBundleId: 'com.app.hamqadam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCksmzI2B_RJx18QoOVmc3SAtir1UYyJYU',
    appId: '1:895538475573:web:b1776ac6bc8b32ebc2b77c',
    messagingSenderId: '895538475573',
    projectId: 'hamqadam-13e2b',
    authDomain: 'hamqadam-13e2b.firebaseapp.com',
    storageBucket: 'hamqadam-13e2b.firebasestorage.app',
    measurementId: 'G-DX6DX6TK4B',
  );
}
