#!/usr/bin/env bash
# Toggle the ML Kit stub that lets this app run on an Apple Silicon iOS simulator.
#
#   tool/simulator.sh on    # stub ML Kit  -> simulator builds work, CNIC OCR does not
#   tool/simulator.sh off   # real ML Kit  -> device/release builds, OCR works
#   tool/simulator.sh status
#
# Why this exists: Google publishes no arm64-simulator slice for the ML Kit pods,
# and Xcode 26 dropped Rosetta simulator destinations, so every iOS 26 simulator
# is arm64-only and the real plugin fails to link. `on` swaps the plugin for
# tool/mlkit_stub, which has the same Dart API and no native side.
#
# NEVER ship a build made with the stub active — card scanning is dead in it.
set -euo pipefail

cd "$(dirname "$0")/.."
OVERRIDES="pubspec_overrides.yaml"

case "${1:-status}" in
  on)
    cat > "$OVERRIDES" <<'YAML'
# GENERATED by tool/simulator.sh — ML Kit is stubbed out so the app can run on an
# arm64 iOS simulator. CNIC card scanning does NOT work while this file exists.
# Remove it (tool/simulator.sh off) before building for a device or for release.
dependency_overrides:
  google_mlkit_text_recognition:
    path: tool/mlkit_stub
YAML
    flutter pub get
    rm -rf ios/Pods ios/Podfile.lock
    # CocoaPods needs a UTF-8 locale or it dies in unicode_normalize.
    (cd ios && LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 pod install)
    echo "✅ ML Kit stubbed. Simulator builds will work; CNIC OCR will not."
    ;;
  off)
    rm -f "$OVERRIDES"
    flutter pub get
    rm -rf ios/Pods ios/Podfile.lock
    # CocoaPods needs a UTF-8 locale or it dies in unicode_normalize.
    (cd ios && LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 pod install)
    echo "✅ Real ML Kit restored. Simulator builds will fail to link; use a device."
    ;;
  status)
    if [ -f "$OVERRIDES" ]; then
      echo "ML Kit: STUBBED (simulator-ready, no OCR)"
    else
      echo "ML Kit: REAL (device-only, OCR works)"
    fi
    ;;
  *)
    echo "usage: tool/simulator.sh [on|off|status]" >&2
    exit 2
    ;;
esac
